### ISSUE TITLE
Support typed actor

### ISSUE THREAD

**Issue by negokaz** [lerna-stack/akka-entity-replication#44]
## Objectives

- Prevent bugs caused by type mismatch
- Improve productivity via code completion

## Not To Do

- Use typed actor for internal implements (refactoring)

## To Do

('1d = 6h)

- [x] [2d] introduce mima #49
- [x] [1d] design typed API #53 
- **API definition** [11h/11h]
    - [x] [2h] ReplicatedEntityBehavior group #54 
        - ReplicatedEntityBehavior
        - Effect
        - ReplicationId
    - [x] [1h] ClusterReplicationSettings group #56 
        - number-of-shards
    - [x] [1h] ReplicatedEntity group #57
    - [x] [2h] ReplicatedEntityBehaviorTestKit group #58 
        - ReplicatedEntityBehaviorTestKit
    - [x] ReplicationEnvelopeMesageExtractor group
        - ~~ReplicationEnvelopeMesageExtractor~~ (classic API of akka-entity-replication doesn't support MessageExtractor: we should implement `extractShardId` an `extractEntityId`)
    - [x] [2h] ReplicatedEntityRef group #59
        - ReplicatedEntityRef
    - [x] [1h] ClusterReplication group #60 
        - ClusterReplication
    - [x] [2h] AtLeastOnceComplete group #61 
        - AtLeastOnceComplete
- **Implementation** [3d/19d]
    - [x] [4d] ReplicatedEntityBehavior group #62, #64
      - ReplicatedEntityBehavior
      - Effect
      - ReplicationId
    - [x] ~~ClusterReplicationSettings group~~ (implemented in #56)
    - [x] [2d] ReplicatedEntity group #65
        - ReplicatedEntity
        - ~~ReplicatedEntityContext~~ (implemented in #57)
        - ReplicatedEntityTypeKey
    - [x] ~~ReplicationEnvelopeMesageExtractor group~~ (implemented in #66)
    - [x] [3d] ReplicatedEntityRef group #67
        - ReplicatedEntityRef
    - [x] [2d] ClusterReplication group #66 
        - ClusterReplication
    - [x] [2d] AtLeastOnceComplete group #68
        - AtLeastOnceComplete
    - [x] [3d] ReplicatedEntityBehaviorTestKit group #70, #69
        - ReplicatedEntityBehaviorTestKit
    - [x] [3d] multi-jvm test #79
- [x] [1d] update implementation guide #53
